[package]
name = "wartooth"
version = "0.1.0"
authors = ["Casey Marshall <github@cmars.tech>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-process = "0.1"

